 platform :ios, '13.0'

target 'UrgentSnack' do
  # Comment the next line if you don't want to use dynamic frameworks
  #  use_frameworks!

  pod 'RxSwift', '6.0.0-rc.2'
  pod 'RxCocoa', '6.0.0-rc.2'
end
