# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UrgentSnack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UrgentSnack

  target 'UrgentSnackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UrgentSnackUITests' do
    # Pods for testing
  end

end
